name: Injest Starter Media

on:
  workflow_dispatch: # This has to be triggered manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-pipeline
        uses: appleboy/ssh-action@v1
        with:
          host: 35.153.127.153
          username: ec2-user
          key: ${{ secrets.LABSUSERPEM }}
          script: |
            cd /LiamRanaIsaac
            sudo bash /LiamRanaIsaac/scripts/addStarterMedia.sh
