name: Reset Redis Database

on:
  workflow_dispatch: # This has to be triggered manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-pipeline
        uses: appleboy/ssh-action@v1
        with:
          host: 13.220.215.38
          username: ec2-user
          key: ${{ secrets.LABSUSERPEM }}
          script: |
            cd /LiamRanaIsaac
            ./scripts/resetDB.sh
